### ISSUE TITLE
Ubuntu 16.04/ros kinetic

### ISSUE THREAD

**Issue by l00f00** [HLDS-GIT/hls_lfom_tof_driver#1]
Hi, i'm currently using v2.3 in ubuntu following the steps in the manual, any chance to have the sdk compatible to ubuntu 20LTS and ros noetic or later versions ?

The actual distribution 16.04 is abandoned and kinetic repositories are problematic.
Fixing the dependencies for openpose/ros is very time consuming for the old ubuntu version 16.04/kinetic.

Having HumanCounterPro also for linux would be a nice option, stitching is an  important function to have at hand.

Do you have suggestion for the dev env setup tailored to debian or debian/ubuntu?

**Comment by HLDS-GIT** [comment]
Thank you for your interest in my product.
We have confirmed that no problems so far with Ubuntu 18.04 LTS and Ros Melodic Morenia.
Please refer to the manual in the sdk for dev env setup.

**Comment by l00f00** [comment]
Thank you for the quick answer!
I've started in a fresh ubuntu 18 with ros melodic. Is there any chance to have human counter PRO features for Linux ?

**Comment by HLDS-GIT** [comment]
Please contact us through the product homepage about human counter PRO.
